export interface Product {
  id: string
  name: string
  category: "iPhone" | "AirPods" | "VR" | "iPad"
  series?: string
  originalPrice: number
  discountedPrice: number
  discount: number
  image: string
  description: string
  features: string[]
  inStock: boolean
  colors?: string[] // Add colors property
}

export const products: Product[] = [
  // iPhone 11 Series
  {
    id: "iphone-11",
    name: "iPhone 11",
    category: "iPhone",
    series: "iPhone 11",
    originalPrice: 699,
    discountedPrice: 280,
    discount: 60,
    image: "/images/iphone-11.jpg",
    description: "The iPhone 11 features a 6.1-inch Liquid Retina display and dual-camera system.",
    features: ['6.1" Liquid Retina Display', "Dual Camera System", "A13 Bionic Chip", "Face ID"],
    inStock: true,
    colors: ["Black", "White", "Red", "Yellow", "Green", "Purple"],
  },
  {
    id: "iphone-11-pro",
    name: "iPhone 11 Pro",
    category: "iPhone",
    series: "iPhone 11",
    originalPrice: 999,
    discountedPrice: 289,
    discount: 71,
    image: "/images/iphone-11-pro.jpg",
    description: "iPhone 11 Pro with triple-camera system and Super Retina XDR display.",
    features: ['5.8" Super Retina XDR', "Triple Camera System", "A13 Bionic Chip", "Face ID"],
    inStock: true,
    colors: ["Space Gray", "Silver", "Gold", "Midnight Green"],
  },
  {
    id: "iphone-11-pro-max",
    name: "iPhone 11 Pro Max",
    category: "iPhone",
    series: "iPhone 11",
    originalPrice: 1099,
    discountedPrice: 299,
    discount: 73,
    image: "/images/iphone-11-pro-max.jpg",
    description: "The largest iPhone 11 with 6.5-inch Super Retina XDR display.",
    features: ['6.5" Super Retina XDR', "Triple Camera System", "A13 Bionic Chip", "Face ID"],
    inStock: true,
    colors: ["Space Gray", "Silver", "Gold", "Midnight Green"],
  },
  // iPhone 12 Series
  {
    id: "iphone-12",
    name: "iPhone 12",
    category: "iPhone",
    series: "iPhone 12",
    originalPrice: 799,
    discountedPrice: 320,
    discount: 60,
    image: "/images/iphone-12.jpg",
    description: "iPhone 12 with 5G capability and Ceramic Shield front.",
    features: ['6.1" Super Retina XDR', "5G Capable", "A14 Bionic Chip", "Ceramic Shield"],
    inStock: true,
    colors: ["Black", "White", "Red", "Green", "Blue", "Purple"],
  },
  {
    id: "iphone-12-mini",
    name: "iPhone 12 Mini",
    category: "iPhone",
    series: "iPhone 12",
    originalPrice: 699,
    discountedPrice: 330,
    discount: 53,
    image: "/images/iphone-12-mini.jpg",
    description: "Compact iPhone 12 with 5.4-inch display.",
    features: ['5.4" Super Retina XDR', "5G Capable", "A14 Bionic Chip", "Ceramic Shield"],
    inStock: true,
    colors: ["Black", "White", "Red", "Green", "Blue", "Purple"],
  },
  {
    id: "iphone-12-pro",
    name: "iPhone 12 Pro",
    category: "iPhone",
    series: "iPhone 12",
    originalPrice: 999,
    discountedPrice: 344,
    discount: 66,
    image: "/images/iphone-12-pro.jpg",
    description: "iPhone 12 Pro with ProRAW and LiDAR Scanner.",
    features: ['6.1" Super Retina XDR', "Triple Camera + LiDAR", "A14 Bionic Chip", "ProRAW"],
    inStock: true,
    colors: ["Graphite", "Silver", "Gold", "Pacific Blue"],
  },
  {
    id: "iphone-12-pro-max",
    name: "iPhone 12 Pro Max",
    category: "iPhone",
    series: "iPhone 12",
    originalPrice: 1099,
    discountedPrice: 350,
    discount: 68,
    image: "/images/iphone-12-pro-max.jpg",
    description: "The largest iPhone 12 with advanced camera system.",
    features: ['6.7" Super Retina XDR', "Triple Camera + LiDAR", "A14 Bionic Chip", "ProRAW"],
    inStock: true,
    colors: ["Graphite", "Silver", "Gold", "Pacific Blue"],
  },
  // iPhone 13 Series
  {
    id: "iphone-13",
    name: "iPhone 13",
    category: "iPhone",
    series: "iPhone 13",
    originalPrice: 799,
    discountedPrice: 360,
    discount: 55,
    image: "/images/iphone-13.jpg",
    description: "iPhone 13 with improved battery life and camera system.",
    features: ['6.1" Super Retina XDR', "Dual Camera System", "A15 Bionic Chip", "Cinematic Mode"],
    inStock: true,
    colors: ["Pink", "Blue", "Midnight", "Starlight", "Red"],
  },
  {
    id: "iphone-13-mini",
    name: "iPhone 13 Mini",
    category: "iPhone",
    series: "iPhone 13",
    originalPrice: 699,
    discountedPrice: 380,
    discount: 46,
    image: "/images/iphone-13-mini.jpg",
    description: "Compact iPhone 13 with powerful performance.",
    features: ['5.4" Super Retina XDR', "Dual Camera System", "A15 Bionic Chip", "Cinematic Mode"],
    inStock: true,
    colors: ["Pink", "Blue", "Midnight", "Starlight", "Red"],
  },
  {
    id: "iphone-13-pro",
    name: "iPhone 13 Pro",
    category: "iPhone",
    series: "iPhone 13",
    originalPrice: 999,
    discountedPrice: 399,
    discount: 60,
    image: "/images/iphone-13-pro.jpg",
    description: "iPhone 13 Pro with ProMotion display and macro photography.",
    features: ['6.1" ProMotion Display', "Triple Camera + LiDAR", "A15 Bionic Chip", "Macro Photography"],
    inStock: true,
    colors: ["Graphite", "Gold", "Silver", "Sierra Blue"],
  },
  {
    id: "iphone-13-pro-max",
    name: "iPhone 13 Pro Max",
    category: "iPhone",
    series: "iPhone 13",
    originalPrice: 1099,
    discountedPrice: 420,
    discount: 62,
    image: "/images/iphone-13-pro-max.jpg",
    description: "The ultimate iPhone 13 with the largest display.",
    features: ['6.7" ProMotion Display', "Triple Camera + LiDAR", "A15 Bionic Chip", "Macro Photography"],
    inStock: true,
    colors: ["Graphite", "Gold", "Silver", "Sierra Blue"],
  },
  // iPhone 14 Series
  {
    id: "iphone-14",
    name: "iPhone 14",
    category: "iPhone",
    series: "iPhone 14",
    originalPrice: 799,
    discountedPrice: 450,
    discount: 44,
    image: "/images/iphone-14.jpg",
    description: "iPhone 14 with Emergency SOS via satellite.",
    features: ['6.1" Super Retina XDR', "Dual Camera System", "A15 Bionic Chip", "Emergency SOS"],
    inStock: true,
    colors: ["Midnight", "Purple", "Starlight", "Red", "Blue"],
  },
  {
    id: "iphone-14-plus",
    name: "iPhone 14 Plus",
    category: "iPhone",
    series: "iPhone 14",
    originalPrice: 899,
    discountedPrice: 465,
    discount: 48,
    image: "/images/iphone-14-plus.jpg",
    description: "iPhone 14 Plus with larger 6.7-inch display.",
    features: ['6.7" Super Retina XDR', "Dual Camera System", "A15 Bionic Chip", "Emergency SOS"],
    inStock: true,
    colors: ["Midnight", "Purple", "Starlight", "Red", "Blue"],
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    category: "iPhone",
    series: "iPhone 14",
    originalPrice: 999,
    discountedPrice: 459,
    discount: 54,
    image: "/images/iphone-14-pro.jpg",
    description: "iPhone 14 Pro with Dynamic Island and Always-On display.",
    features: ['6.1" Always-On Display', "Dynamic Island", "A16 Bionic Chip", "48MP Main Camera"],
    inStock: true,
    colors: ["Space Black", "Silver", "Gold", "Deep Purple"],
  },
  {
    id: "iphone-14-pro-max",
    name: "iPhone 14 Pro Max",
    category: "iPhone",
    series: "iPhone 14",
    originalPrice: 1099,
    discountedPrice: 488,
    discount: 56,
    image: "/images/iphone-14-pro-max.jpg",
    description: "The most advanced iPhone 14 with the largest display.",
    features: ['6.7" Always-On Display', "Dynamic Island", "A16 Bionic Chip", "48MP Main Camera"],
    inStock: true,
    colors: ["Space Black", "Silver", "Gold", "Deep Purple"],
  },
  // iPhone 15 Series
  {
    id: "iphone-15",
    name: "iPhone 15",
    category: "iPhone",
    series: "iPhone 15",
    originalPrice: 799,
    discountedPrice: 535,
    discount: 33,
    image: "/images/iphone-15.jpg",
    description: "iPhone 15 with USB-C and Dynamic Island.",
    features: ['6.1" Super Retina XDR', "Dynamic Island", "A16 Bionic Chip", "USB-C"],
    inStock: true,
    colors: ["Black", "Blue", "Green", "Yellow", "Pink"],
  },
  {
    id: "iphone-15-plus",
    name: "iPhone 15 Plus",
    category: "iPhone",
    series: "iPhone 15",
    originalPrice: 899,
    discountedPrice: 535,
    discount: 40,
    image: "/images/iphone-15-plus.jpg",
    description: "iPhone 15 Plus with larger display and USB-C.",
    features: ['6.7" Super Retina XDR', "Dynamic Island", "A16 Bionic Chip", "USB-C"],
    inStock: true,
    colors: ["Black", "Blue", "Green", "Yellow", "Pink"],
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "iPhone",
    series: "iPhone 15",
    originalPrice: 999,
    discountedPrice: 545,
    discount: 45,
    image: "/images/iphone-15-pro.jpg",
    description: "iPhone 15 Pro with titanium design and Action Button.",
    features: ['6.1" ProMotion Display', "Titanium Design", "A17 Pro Chip", "Action Button"],
    inStock: true,
    colors: ["Black Titanium", "White Titanium", "Blue Titanium", "Natural Titanium"],
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "iPhone",
    series: "iPhone 15",
    originalPrice: 1199,
    discountedPrice: 560,
    discount: 53,
    image: "/images/iphone-15-pro-max.jpg",
    description: "The ultimate iPhone 15 with titanium and 5x telephoto.",
    features: ['6.7" ProMotion Display', "Titanium Design", "A17 Pro Chip", "5x Telephoto"],
    inStock: true,
    colors: ["Black Titanium", "White Titanium", "Blue Titanium", "Natural Titanium"],
  },
  // iPhone 16 Series
  {
    id: "iphone-16",
    name: "iPhone 16",
    category: "iPhone",
    series: "iPhone 16",
    originalPrice: 799,
    discountedPrice: 600,
    discount: 25,
    image: "/images/iphone-16.jpg",
    description: "Latest iPhone 16 with Apple Intelligence.",
    features: ['6.1" Super Retina XDR', "Apple Intelligence", "A18 Chip", "Camera Control"],
    inStock: true,
    colors: ["Black", "White", "Green", "Purple", "Yellow"],
  },
  {
    id: "iphone-16-plus",
    name: "iPhone 16 Plus",
    category: "iPhone",
    series: "iPhone 16",
    originalPrice: 899,
    discountedPrice: 610,
    discount: 32,
    image: "/images/iphone-16-plus.jpg",
    description: "iPhone 16 Plus with larger display and Apple Intelligence.",
    features: ['6.7" Super Retina XDR', "Apple Intelligence", "A18 Chip", "Camera Control"],
    inStock: true,
    colors: ["Black", "White", "Green", "Purple", "Yellow"],
  },
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    category: "iPhone",
    series: "iPhone 16",
    originalPrice: 999,
    discountedPrice: 630,
    discount: 37,
    image: "/images/iphone-16-pro.jpg",
    description: "iPhone 16 Pro with advanced Apple Intelligence features.",
    features: ['6.3" ProMotion Display', "Apple Intelligence", "A18 Pro Chip", "Camera Control"],
    inStock: true,
    colors: ["Space Black", "Silver", "Gold", "Titanium Gray"],
  },
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    category: "iPhone",
    series: "iPhone 16",
    originalPrice: 1199,
    discountedPrice: 650,
    discount: 46,
    image: "/images/iphone-16-pro-max.jpg",
    description: "The most advanced iPhone with the largest display.",
    features: ['6.9" ProMotion Display', "Apple Intelligence", "A18 Pro Chip", "Camera Control"],
    inStock: true,
    colors: ["Space Black", "Silver", "Gold", "Titanium Gray"],
  },
  // AirPods
  {
    id: "airpods-2nd-gen",
    name: "AirPods (2nd Generation)",
    category: "AirPods",
    originalPrice: 129,
    discountedPrice: 30,
    discount: 77,
    image: "/images/airpods-2nd-gen.jpg",
    description: 'Classic AirPods with H1 chip and "Hey Siri" support.',
    features: ["H1 Chip", "Hey Siri", "24-hour battery", "Lightning Case"],
    inStock: true,
  },
  {
    id: "airpods-pro",
    name: "AirPods Pro (2nd Generation)",
    category: "AirPods",
    originalPrice: 249,
    discountedPrice: 80,
    discount: 68,
    image: "/images/airpods-pro.jpg",
    description: "AirPods Pro with Active Noise Cancellation.",
    features: ["Active Noise Cancellation", "Transparency Mode", "Spatial Audio", "MagSafe Case"],
    inStock: true,
  },
  {
    id: "airpods-4",
    name: "AirPods 4",
    category: "AirPods",
    originalPrice: 179,
    discountedPrice: 200,
    discount: -12, // This is actually higher than original price
    image: "/images/airpods-4.jpg",
    description: "Latest AirPods 4 with improved design and features.",
    features: ["H2 Chip", "Personalized Spatial Audio", "USB-C Case", "Improved Fit"],
    inStock: true,
  },
  // VR
  {
    id: "elecom-vr",
    name: "Elecom VR Headset",
    category: "VR",
    originalPrice: 299,
    discountedPrice: 70,
    discount: 77,
    image: "/images/elecom-vr.jpg",
    description: "Immersive VR experience with high-quality display.",
    features: ["High Resolution Display", "Comfortable Design", "Wide FOV", "Adjustable Straps"],
    inStock: true,
  },
  // iPads
  {
    id: "ipad-mini-5th-gen",
    name: "iPad mini (5th Generation)",
    category: "iPad",
    originalPrice: 399,
    discountedPrice: 399,
    discount: 0,
    image: "/images/ipad-mini-5th-gen.jpg",
    description: "Compact iPad mini with A12 Bionic chip.",
    features: ['7.9" Retina Display', "A12 Bionic Chip", "Apple Pencil Support", "Touch ID"],
    inStock: true,
  },
  {
    id: "ipad-mini-6th-gen",
    name: "iPad mini (6th Generation)",
    category: "iPad",
    originalPrice: 499,
    discountedPrice: 499,
    discount: 0,
    image: "/images/ipad-mini-6th-gen.jpg",
    description: "Latest iPad mini with A15 Bionic chip and USB-C.",
    features: ['8.3" Liquid Retina Display', "A15 Bionic Chip", "USB-C", "Apple Pencil 2 Support"],
    inStock: true,
  },
]

export const categories = ["All", "iPhone", "AirPods", "VR", "iPad"] as const
export const iPhoneSeries = [
  "All",
  "iPhone 11",
  "iPhone 12",
  "iPhone 13",
  "iPhone 14",
  "iPhone 15",
  "iPhone 16",
] as const
